export const btnVariants = ['primary', 'transparent', 'transparent-orange'] as const;
export const carModels = [
  'Toyota Camry',
  'Toyota Prius',
  'Toyota Corolla',
  'Honda CR-V',
  'Honda Accord',
  'Honda Pilot',
  'Chevrolet Tahoe',
  'Chevrolet Spark',
  'Ford Escape',
  'Ford Focus',
  'Mercedes-Benz GLE',
  'Mercedes-Benz C-Class',
  'Jeep Cherokee',
  'Jeep Wrangler',
  'BMW 330i',
  'BMW X1',
  'Subaru Forester',
  'Subaru Impreza',
  'Nissan Sentra',
  'Nissan Leaf',
  'Nissan Almera',
  'Cadillac CT5',
  'Cadillac CT4',
  'Volkswagen Golf',
  'Volkswagen Passat',
  'Audi A1',
  'Audi A6',
  'Audi A4',
  'GMC CANYON',
  'GMC TERRAIN',
  'Dodge Charger',
  'Dodge Challenger',
  'Hyundai Tucson',
  'Hyundai Elantra',
  'Hyundai Solaris',
  'Hyundai Sonata',
  'Mazda 3',
  'Mazda 6',
  'Land Rover Defender',
  'Tesla Model 3',
  'Tesla Model X',
  'Tesla Model S',
  'Kia Rio',
  'Kia Optima',
  'Chrysler 300',
  'Mitsubishi Lancer',
  'Mitsubishi Outlander',
  'Genesis G70',
  'Suzuki Vitara',
  'Suzuki Gimny',
  'Renault Logan',
  'Peugeot 2008',
  'Peugeot 3008',
  'Citroen',
] as const;

export const citiesListData = [
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Philadelphia',
  'Phoenix',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'San Francisco',
  'Indianapolis',
  'Columbus',
  'Fort Worth',
  'Charlotte',
  'Seattle',
  'Denver',
  'El Paso',
  'Detroit',
  'Washington',
  'Boston',
  'Memphis',
  'Nashville',
  'Portland, Ore.',
  'Oklahoma City',
  'Las Vegas',
  'Baltimore',
  'Louisville',
  'Milwaukee',
  'Albuquerque',
  'Tucson',
  'Fresno',
  'Sacramento',
  'Kansas City, Mo.',
  'Long Beach',
  'Mesa',
  'Atlanta',
  'Colorado Springs',
  'Virginia Beach',
  'Raleigh',
  'Omaha',
  'Miami',
  'Oakland',
  'Minneapolis',
  'Tulsa',
  'Wichita',
  'New Orleans',
  'Arlington, Texas',
  '',
] as const;

export const transmission = ['AT', 'MT'] as const;
export const numberOfSeats = [4, 5] as const;
export const deposit = [100, 150, 200, 250, 300] as const;
export const carType = ['Sedan', 'Compact', 'Economy', 'Midsize', 'FullSize', 'Mini', 'Luxury'] as const;
export const capacity = ['2', '3-5', '6+'] as const;
export const VEHICLES_PER_PAGE = 6;
